### ISSUE TITLE
mac上编译失败

### ISSUE THREAD

**Issue by tangjinou** [yksten/struct#1]
jiuxian.tjo@B-Q3GDMD6M-2146 build % make
Scanning dependencies of target struct2x
[  9%] Building CXX object CMakeFiles/struct2x.dir/src/struct2x.cpp.o
In file included from /Users/jiuxian.tjo/git/c++_project/struct2x/src/struct2x.cpp:1:
/Users/jiuxian.tjo/git/c++_project/struct2x/./include/struct2x.h:204:71: error: use of undeclared identifier '_atoi64'
                static inline int64_t strto(const char* str) { return _atoi64(str); }
                                                                      ^
/Users/jiuxian.tjo/git/c++_project/struct2x/./include/struct2x.h:209:82: error: use of undeclared identifier '_atoi64'
                static inline uint64_t strto(const char* str) { return (uint64_t)_atoi64(str); }
                                                                                 ^
/Users/jiuxian.tjo/git/c++_project/struct2x/./include/struct2x.h:235:81: error: implicit instantiation of undefined template
      'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
                static inline const char* tostr(const std::string& v) { return v.c_str(); }

**Comment by yksten** [comment]
抱歉，刚刚看到，我修正了。再编译下试试。 @tangjinou
