### ISSUE TITLE
请问这个项目的开源协议是啥？

### ISSUE THREAD

**Issue by JimYang365** [yksten/struct#3]
您好，打算将您的代码用于商业用途，不知这个项目的开源协议是哪个？

我看里面用到了 cJSON 和 protobuf 的代码，是 MIT 协议么？

谢谢！

**Comment by yksten** [comment]
欢迎大家使用。

**Comment by JimYang365** [comment]
多谢！

**Comment by JimYang365** [comment]
如果方便，给这个项目加个开源协议吧，希望是MIT  ^__^
